version: '3.7'

services:
  postgres:
    image: postgres
    container_name: pg_container
    volumes:
      - $HOME/pg_data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: letmein
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: letmein
    ports:
      - "80:80"